#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

NO_BUILD=""

if [[ "${1:-}" == "--no-build" ]]; then
  shift
  NO_BUILD="true"
fi

TARGET_HOST="$(cat pi-ip.txt)"
if [[ "${1:-}" == "--target-host" ]]; then
  TARGET_HOST="$2"
  shift 2
fi

TARGET_PATH="."
TARGET_ARCH="aarch64-unknown-linux-gnu"
BINARY_NAME="boxen-client"
SOURCE_PATH="./target/${TARGET_ARCH}/debug/${BINARY_NAME}"

if [[ -z "${NO_BUILD}" ]]; then
  cross build --target="${TARGET_ARCH}"
fi

rsync "${SOURCE_PATH}" "${TARGET_HOST}:${TARGET_PATH}"
