#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

TARGET_HOST="$(cat pi-ip.txt)"
TARGET_PATH="."
TARGET_ARCH="aarch64-unknown-linux-gnu"
BINARY_NAME="webrtc-app"
SOURCE_PATH="./target/${TARGET_ARCH}/debug/${BINARY_NAME}"

cross build --target="${TARGET_ARCH}"
rsync "${SOURCE_PATH}" "${TARGET_HOST}:${TARGET_PATH}"
