#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

TARGET_HOST="$(cat pi-ip.txt)"
if [[ "${1:-}" == "--target-host" ]]; then
  TARGET_HOST="$2"
  shift 2
fi

TARGET_PATH="."

if [[ "${1:-}" == "--no-build" ]]; then
  shift
else
  ./build-to-pi --target-host "${TARGET_HOST}"
fi

ssh -t "${TARGET_HOST}" "cd ${TARGET_PATH} && ./boxen-client $@" # GST_DEBUG=\"*webrtc*:7\"
