#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

#LD_LIBRARY_PATH="$(cat ~/.libnice-library-path.txt)" cargo run -- "$@" # GST_DEBUG="*webrtc*:7"
LD_LIBRARY_PATH="$(cat ~/.libnice-library-path.txt)" target/debug/boxen-client "$@" # GST_DEBUG="*webrtc*:7"
