#!/usr/bin/env bash
# Watch the logs of this script with:
# $ journalctl --user -u boxen-client.service -f

# Get the hardware id of the seeed device
CARD_ID="$(aplay -l | grep seeed | cut -d ' ' -f 2 | cut -d ':' -f 1)"

# Setup input/output device on every boot, since the device id changes sometimes
echo "alsasrc device=\"hw:$CARD_ID\"" > input.txt
echo "alsasink device=\"hw:$CARD_ID\"" > output.txt

# Set a reasonable volume
amixer -c "$CARD_ID" sset Speaker "79%"

# Run the service
./boxen-client
