#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

TARGET_HOST="$1"

scp usbwifi usbwifi.rules "${TARGET_HOST}:."
ssh -t "${TARGET_HOST}" "sed -i \"s!__HOME__!\${HOME}!g\" usbwifi.rules &&
sudo cp usbwifi.rules /etc/udev/rules.d/99-usbwifi.rules &&
rm usbwifi.rules &&
sed -i \"s/__USER__/\${USER}/g\" usbwifi &&
sed -i \"s!__HOME__!\${HOME}!g\" usbwifi &&
sudo apt install -y usbmount at &&
sudo snap install yq &&
sudo mkdir -p /etc/systemd/system/systemd-udevd.service.d &&
echo -e '[Service]\nPrivateMounts=no' | sudo tee /etc/systemd/system/systemd-udevd.service.d/00-private-mounts-no.conf &&
sudo udevadm control --reload-rules &&
sudo udevadm trigger &&
sudo systemctl daemon-reexec &&
sudo service systemd-udevd restart"
