#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

TARGET_HOST="$1"

./build-debian-package

scp usbwifi usbwifi.rules usbmount_0.0.24_all.deb "${TARGET_HOST}:."

# Install usbmount to automount usb sticks
# Set udevd PrivateMounts=no to allow usbmount to mount correctly
# Restart daemon-reexec and systemd-udevd to make sure PrivateMounts gets loaded
# Install yq to manipulate yaml-files
# Add the usbwifi.rules udev rule
# Reload the udev rules to make sure usbwifi.rules gets loaded

ssh -t "${TARGET_HOST}" "sed -i \"s!__HOME__!\${HOME}!g\" usbwifi.rules &&
sudo cp usbwifi.rules /etc/udev/rules.d/99-usbwifi.rules &&
rm usbwifi.rules &&
sed -i \"s/__USER__/\${USER}/g\" usbwifi &&
sed -i \"s!__HOME__!\${HOME}!g\" usbwifi &&
sudo apt install -y ./usbmount_0.0.24_all.deb &&
sudo apt install -y at &&
sudo snap install yq &&
sudo mkdir -p /etc/systemd/system/systemd-udevd.service.d &&
echo -e '[Service]\nPrivateMounts=no' | sudo tee /etc/systemd/system/systemd-udevd.service.d/00-private-mounts-no.conf &&
sudo udevadm control --reload-rules &&
sudo udevadm trigger &&
sudo systemctl daemon-reexec &&
sudo service systemd-udevd restart"
