FROM aarch64-unknown-linux-gnu-21-04-base

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes \
    gstreamer1.0-tools:arm64 \
    gstreamer1.0-nice:arm64 \
    gstreamer1.0-plugins-bad:arm64 \
    gstreamer1.0-plugins-ugly:arm64 \
    gstreamer1.0-plugins-good:arm64 \
    libgstreamer-plugins-bad1.0-dev:arm64 \
    libgstreamer1.0-dev:arm64 \
    libglib2.0-dev:arm64 \
    libsoup2.4-dev:arm64 \
    libjson-glib-dev:arm64

#RUN ls /usr/lib/arm64*
#RUN ls /usr/lib/aarch64-linux-gnu/
ENV PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu=/usr/lib/aarch64-linux-gnu/pkgconfig

